language: c
sudo: required
env:
  - OS=fedora-rawhide
  - OS=fedora-latest
  - OS=ubuntu-devel
  - OS=ubuntu-latest
  - OS=ubuntu-lts
services:
  - docker
before_install:
  - docker pull "cangjians/build-essential:${OS}"
  - docker tag "cangjians/build-essential:${OS}" "cangjians/build-essential:latest"
  - docker build --tag "cangjians/libcangjie" .
script:
  - docker run --interactive --tty --rm "cangjians/libcangjie" make check distcheck
