language: c
sudo: required
branches:
  only:
    - master
env:
  - OS=fedora-rawhide
  - OS=fedora-latest
  - OS=ubuntu-devel
  - OS=ubuntu-latest
  - OS=ubuntu-lts
services:
  - docker
before_install:
  - docker pull "cangjians/build-essential:${OS}"
  - docker build --build-arg OS=${OS} --tag "cangjians/libcangjie:${OS}" .
script:
  - docker run --rm "cangjians/libcangjie:${OS}" make distcheck
