language: c
sudo: required
env:
  - OS=ubuntu-16.04
  - OS=fedora-25
  - OS=opensuse-leap
services:
  - docker
before_install:
  - |
    sudo docker pull "cangjians/build-essential:${OS}"
    sudo docker tag "cangjians/build-essential:${OS}" "cangjians/build-essential:latest"
    sudo docker build -t "cangjians/libcangjie" .
script:
  - docker run -it --rm "cangjians/libcangjie" make check distcheck
