language: c
sudo: required
env:
  - OS=fedora-rawhide
  - OS=fedora-latest
  - OS=ubuntu-devel
  - OS=ubuntu-latest
  - OS=ubuntu-lts
services:
  - docker
before_install:
  - |
    sudo docker pull "cangjians/build-essential:${OS}"
    sudo docker tag "cangjians/build-essential:${OS}" "cangjians/build-essential:latest"
    sudo docker build -t "cangjians/libcangjie" .
script:
  - docker run -it --rm "cangjians/libcangjie" make check distcheck
